### ISSUE TITLE
有错别字

### ISSUE THREAD

**Issue by AlexanderInHUST** [dyinnz/The_excellent_HUSTer_has_no_boy_or_girl_friend#1]
他却不会受此影响。

我问她：你到底怎么保持一颗平常心，面对这么多作业实验考试，你怎么能一一完成并怒刷加权，不会干扰到你的内心？

他笑，说：你小时候没有读过名人传记啊？尤其是牛顿贝多芬尼采爱迪生列宁罗斯福？

她 -> 他

**Comment by dyinnz** [comment]
corrected
